# wrangler.toml
name = "gs-work-api"
type = "javascript"
account_id = "b2808a270d96e4ffd3b1d90e449b5fa7"
route = ""
workers_dev = true

[site]
bucket = "./public"
entry-point = "."


[build]
command = "npm run build"

[build.upload]
format = "service-worker"
main = "./build/index.js"